# Generated by Django 5.0.6 on 2024-05-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Spec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.CharField(blank=True, max_length=10000, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='posters/tv/season')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.CharField(blank=True, max_length=10000, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='posters/tv/episode')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tv.season')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=255)),
                ('adult', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.CharField(blank=True, max_length=10000, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='posters/tv/series')),
                ('slug', models.SlugField(blank=True, help_text='Leave Blank', max_length=500, null=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, to='Spec.category')),
                ('genre', models.ManyToManyField(blank=True, to='Spec.genre')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Spec.quality')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tv.series'),
        ),
    ]
